platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run dist

test: off

branches:
  only:
    - master

environment:
  GH_TOKEN: 
    secure: pfx5gzq0s31AIdaL6NPJCnZwOnUVIyqsqVa48Ea9/qIyx2vJtGhKVglaeCmAGYen

# 322fce4f2ac52723efe58a21409646a924b03ce6
deploy:
  release: myproduct-v1
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: pfx5gzq0s31AIdaL6NPJCnZwOnUVIyqsqVa48Ea9/qIyx2vJtGhKVglaeCmAGYen # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only